parameters:
#    celmedia_crm_canjeador_codigos.example.class: Celmedia\CrmCanjeadorCodigosBundle\Example

services:
  

    celmedia_crm_canjeador_codigos.admin.aplicacion:
        class: Celmedia\CrmCanjeadorCodigosBundle\Admin\AplicacionAdmin
        arguments: [~, Celmedia\CrmCanjeadorCodigosBundle\Entity\Aplicacion, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Crm, label: Aplicacion}
