celmedia_admin_theme_homepage:
    path:     /manager
    defaults: { _controller: CelmediaAdminThemeBundle:Default:index }

celmedia_admin_theme_participantes:
    path:     /manager/participantes
    defaults: { _controller: CelmediaAdminThemeBundle:Default:participantes }

celmedia_admin_theme_codigos:
    path:     /manager/codigos
    defaults: { _controller: CelmediaAdminThemeBundle:Default:codigos }

