parameters:
#    celmedia_admin_theme.example.class: Celmedia\AdminThemeBundle\Example

services:
#    celmedia_admin_theme.example:
#        class: %celmedia_admin_theme.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
