# src/Acme/BlogBundle/Resources/config/validation.yml
Celmedia\PortalBundle\Entity\Campana:
    properties:
        nombre:
            - NotBlank: ~
        ciudades:
            - NotBlank: ~
            - Count:
                min: 1
                minMessage: "Debe escoger minimo una ciudad"

# src/Acme/BlogBundle/Resources/config/validation.yml
Celmedia\PortalBundle\Entity\Mensaje:
    properties:
        fechaEnvio:
            - NotBlank: ~
        cantidadMensajes:
            - NotBlank: ~
        contenidoMensaje:
            - NotBlank: ~
        # fechaIncio:
        #     - NotBlank: ~
        # fechaFin:
        #     - NotBlank: ~

