 
services:
    sonata.admin.tipoTarjeta:
        class: Celmedia\PortalBundle\Admin\TipoTarjetaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Configuraciones de parametros", label: "Tipos de Tarjetas" }
        arguments:
            - ~
            - Celmedia\PortalBundle\Entity\TipoTarjeta
            - ~
        calls:
            - [ setTranslationDomain, [PortalSmsBundle]]
            
            
    sonata.admin.ciudad:
        class: Celmedia\PortalBundle\Admin\CiudadAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Configuraciones de parametros", label: "Ciudades" }
        arguments:
            - ~
            - Celmedia\PortalBundle\Entity\Ciudad
            - ~
        calls:
            - [ setTranslationDomain, [PortalSmsBundle]]
            
            
     