Celmedia\PortalBundle\Entity\Envio:
    type: entity
    table: envio
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        fechaEnvio:
            type: datetime          
            nullable: false
        estado:
            type: datetime          
            nullable: false
    oneToOne:
      cliente:
        targetEntity: Cliente
        joinColumn:
          name: cliente_id
          referencedColumnName: id
      campana:
        targetEntity: Campana
        joinColumn:
          name: campana_id
          referencedColumnName: id

    lifecycleCallbacks: {  }
