Celmedia\PortalBundle\Entity\Mensaje:
    type: entity
    table: mensaje
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 100
            fixed: false
            nullable: true
        tipoMensaje:
            type: string
            length: 1
            fixed: false
            nullable: false
        fechaEnvio:
            type: datetime
            nullable: false
        cantidadMensajes:
            type: integer
            nullable: false
        contenidoMensaje:
            type: string
            length: 200
            nullable: false
        tipoTarjeta:
            type: string
            length: 200
            nullable: true

        fechaIncio:
            type: datetime
            nullable: true
        fechaFin:
            type: datetime
            nullable: true
        fechaCreacion:
            type: datetime
            nullable: false
        fechaCumpleanios:
            type: datetime
            nullable: true 

    oneToOne:
        tipo_tarjeta:
          targetEntity: TipoTarjeta
          joinColumn:
            name: tipotarjeta_id
            referencedColumnName: id



    lifecycleCallbacks: {  }
